[
  {
    "cmd": [],
    "name": "RECIPE CRASH (Uncaught exception)",
    "~followup_annotations": [
      "@@@STEP_EXCEPTION@@@",
      "The recipe has crashed at point 'Uncaught exception'!",
      "",
      "Traceback (most recent call last):",
      "  File \"RECIPE_REPO[flutter]/recipe_modules/adhoc_validation/examples/full.py\", line 15, in RunSteps",
      "    api.adhoc_validation.run('dart analyze', validation, {}, {})",
      "  File \"RECIPE_REPO[flutter]/recipe_modules/adhoc_validation/api.py\", line 37, in run",
      "    raise AssertionError(msg)",
      "AssertionError: invalid is not listed in available_validations."
    ]
  },
  {
    "failure": {
      "humanReason": "Uncaught Exception: AssertionError('invalid is not listed in available_validations.',)"
    },
    "name": "$result"
  }
]