[
  {
    "cmd": [],
    "name": "RECIPE CRASH (Uncaught exception)",
    "~followup_annotations": [
      "@@@STEP_EXCEPTION@@@",
      "The recipe has crashed at point 'Uncaught exception'!",
      "",
      "Traceback (most recent call last):",
      "  File \"RECIPE_REPO[flutter]/recipe_modules/repo_util/examples/unsupported.py\", line 17, in RunSteps",
      "    api.path['start_dir'].join('unsupported_repo'))",
      "  File \"RECIPE_REPO[flutter]/recipe_modules/repo_util/api.py\", line 100, in checkout",
      "    raise ValueError('Unsupported repo: %s' % name)",
      "ValueError: Unsupported repo: unsupported_repo"
    ]
  },
  {
    "failure": {
      "humanReason": "Uncaught Exception: ValueError('Unsupported repo: unsupported_repo',)"
    },
    "name": "$result"
  }
]