[
  {
    "cmd": [],
    "name": "RECIPE CRASH (Uncaught exception)",
    "~followup_annotations": [
      "@@@STEP_EXCEPTION@@@",
      "The recipe has crashed at point 'Uncaught exception'!",
      "",
      "Traceback (most recent call last):",
      "  File \"RECIPE_REPO[flutter]/recipe_modules/repo_util/examples/unsupported.py\", line 13, in RunSteps",
      "    api.repo_util.checkout('unsupported_repo', repo_dir)",
      "  File \"RECIPE_REPO[flutter]/recipe_modules/repo_util/api.py\", line 223, in checkout",
      "    raise ValueError('Unsupported repo: %s' % name)",
      "ValueError('Unsupported repo: unsupported_repo')"
    ]
  },
  {
    "failure": {
      "humanReason": "Uncaught Exception: ValueError('Unsupported repo: unsupported_repo')"
    },
    "name": "$result"
  }
]