[
  {
    "cmd": [],
    "name": "RECIPE CRASH (Uncaught exception)",
    "~followup_annotations": [
      "@@@STEP_EXCEPTION@@@",
      "The recipe has crashed at point 'Uncaught exception'!",
      "",
      "Traceback (most recent call last):",
      "  File \"RECIPE_REPO[flutter]/recipes/release/release_publish.py\", line 68, in RunSteps",
      "    assert isValidTag(tag, release_channel)",
      "AssertionError()"
    ]
  },
  {
    "failure": {
      "humanReason": "Uncaught Exception: AssertionError()"
    },
    "name": "$result"
  }
]