[
  {
    "cmd": [],
    "name": "RECIPE CRASH (Uncaught exception)",
    "~followup_annotations": [
      "@@@STEP_EXCEPTION@@@",
      "The recipe has crashed at point 'Uncaught exception'!",
      "",
      "Traceback (most recent call last):",
      "  File \"RECIPE_REPO[flutter]/recipes/devicelab_1_23_0.py\", line 32, in RunSteps",
      "    raise ValueError('Unknown role: %s' % role)",
      "ValueError: Unknown role: unknown"
    ]
  },
  {
    "failure": {
      "humanReason": "Uncaught Exception: ValueError('Unknown role: unknown',)"
    },
    "name": "$result"
  }
]